### ISSUE TITLE
Some issues with your documentation: Fedora server SELinux and firewall

### ISSUE THREAD

**Issue by GrigLars** [KyWa/mineOps#1]
I am loving your series.  I did notice two things on this page regarding a Fedora install:

https://blog.kywa.io/mineops-part-1/

`firewall-cmd --add-port=25565`

should be

`firewall-cmd --add-port=25565/tcp`

otherise, you get an error no protocol is listed.

In addition, on the Fedora server I set up, I had to set SELinux to "permissive" or else I wasn't able to set the firewall OR get minecraft to work The command `getenforce` will tell you what mode you're in, and `setenforce permissive` will set permissive for THAT session, but will reset back to `enabled` on reboot.  

If one wants to permanently fix it, you have to set both:

`/etc/sysconfig/selinux`

You need to set 

`SELINUX=permissive`

or "disabled" if you like, and add it to the command line vua grubby:

`grubby --update-kernel ALL --args selinux=0`

This will remove SELinux on reboot.  Security wise, not the wisest options, but the selinux portion of adding to Mine Ops is probably outside your tutorial's goals.

**Comment by GrigLars** [comment]
Huh, mine was also tested on FedoraServer 35.  It's been a while since I ran a Fedora/CentOS server, since all the devops/SBC world seems to be focused on Ubuntu/Debian based distros at the moment, so I was a little rusty on that end of the distros. Since you're familiar with firewall/SELinux, I'd defer to your experience versus what I encountered. 

I try to approach these with "total new person" cutting and pasting to flush out these errors, as it can often be difficult when one knows "oh, wait, I know what I did wrong," and then forgetting to document. In this case, my rusty experience picked out the tcp issue, since when I last worried about firewalls, iptables (and their commands) was the big player.

**Comment by KyWa** [comment]
I'll run this all again on a fresh install of a server and test all of this again to make sure nothing was missed. I ran this on multiple new instances of servers initially, but I'll test again to be sure.

**Comment by KyWa** [comment]
@GrigLars I just tested on a fresh CentOS 8 Stream VM without issues using these commands straight from the `README.md`:

```
dnf install -y java-17-openjdk
mkdir /opt/minecraft && cd /opt/minecraft
curl -o jq -sL https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x jq
echo "eula=true" > eula.txt
curl -o server.jar $(curl `curl -sL https://launchermeta.mojang.com/mc/game/version_manifest.json | ./jq -r '.latest.release as $release | .versions[] | select (.id == $release) | .url'` | ./jq -r '.downloads.server.url')
firewall-cmd --add-port=25565/tcp
java -Xmx1024M -Xms1024M -jar server.jar nogui
```

I was able to start up and connect from my desktop to the server on my hypervisor. Not sure what issues you saw and would be interested to see what config you had or if there was some other `selinux context` for whichever directory you were running in.
